version: "3.7"

services:
  postgresql:
    container_name: postgresql
    image: debezium/postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - ./config/mysql:/etc/mysql/conf.d/
    environment:
      - MYSQL_ROOT_PASSWORD=root1234
      - MYSQL_DATABASE=debezium
      - MYSQL_USER=userdemo
      - MYSQL_PASSWORD=userpwd