debezium:
  engine-name: cdcstreamingengine
  database-server-name: cdcstreamingserver
  connector-class: io.debezium.connector.mysql.MySqlConnector
  database-hostname: localhost
  database-port: 3306
  database-name: debezium
  database-user: root
  database-password: root1234
  offset-storage-file: ${OFFSET_FILE_DIR}
  database-history-storage-file: ${HISTORY_FILE_DIR}
  schema-include-list:
  table-include-list:
  snapshot-mode:
  plugin-name:
  slot-name:
