spring:
  application:
    name: debezium-core-demo
debezium:
  engine-name: cdcstreamingengine
  database-server-name: cdcstreamingserver
  connector-class: io.debezium.connector.postgresql.PostgresConnector
  database-hostname: localhost
  database-port: 5432
  database-name: postgres
  database-user: postgres
  database-password: postgres
  offset-storage-file: ${OFFSET_FILE_DIR}
  schema-include-list:
  table-include-list:
  snapshot-mode:
  plugin-name:
  slot-name:
#rocketmq:
#  name-server: localhost:9876
#  producer:
#    group: cdc-streaming